### ISSUE TITLE
Add .csv file of accelerometer data in Accelerometer folder.

### ISSUE THREAD

**Issue by RednirgSkizzif** [RednirgSkizzif/HALTHASS#2]
Put a .csv file of accelerometer readings into the Accelerometer folder so that we can tests the gems function.

**Comment by ghost** [comment]
I uploaded zip file that contains Accelerometer data (csv type) with Pasco.
6 channels are collected. Only the first channel is connected to the sensor while the rest 5 channels are grounded.
